# Main application settings.
app:
  APP_NAME:     "mandlebrot"
  APP_VERSION:  "0.0.1"
# Logging settings.
log:
  DEF_LEVEL:     20
  MAX_SIZE:      250000
  MAX_FILES:     3
# Low resoltion image settings.
lres:
  DEF_ITERATIONS: 20
  DEF_PIXELS:     21
  DEF_XMIN:       -2
  DEF_XMAX:       0.5
  DEF_YMIN:       -1.5
  DEF_YMAX:       1.5
hres:
  DEF_ITERATIONS: 40
  DEF_PIXELS:     512
  DEF_XMIN:       -2
  DEF_XMAX:       0.5
  DEF_YMIN:       -1.5
  DEF_YMAX:       1.5
  COL_MAP:        "rainbow"
